spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  jpa:
    hibernate:
      ddl-auto: create
      generate-ddl: true
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
external-service:
  customer-url: ${CUSTOMER_APP_URL}
  transaction-url: ${TRANSACTION_APP_URL}
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: error
    org.hibernate: error