version: '3.7'
networks:
  service-network:
   name: service-network
   driver: bridge
volumes:
  postgres-data:
services:
  account-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: account-service
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./appconfigs/:/config/
    networks:
      - service-network
    depends_on:
      - account-db
    healthcheck:
      test: curl -f http://localhost:8080/api/accounts/check || exit 1
      interval: 1m
      timeout: 10s
      retries: 10
  account-db:
    image: postgres:alpine
    container_name: account-db
    restart: always
    # volumes:
    #  - ./data:/var/lib/postgresql/data
    networks:
      - service-network
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acct_mgt
#      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 10
